language: node_js
node_js: '15'

branches:
  only:
  - master
cache:
  yarn: true
  directories:
    - node_modules
    - .next/cache
before_install:
- yarn upgrade
- pip install --user codecov

install:
- yarn
script:
- yarn coverage

after_success:
  - codecov --file coverage/lcov.info --disable search